### ISSUE TITLE
Unable to configure a controller as a service in ASP.NET Core

### ISSUE THREAD

**Issue by opejanovic** [autofac/Autofac.Configuration#23] opened 2018-10-08 13:00 UTC
Hi,
I am using Autofac.Configuration in .NET 4.7 for injecting Controllers as plugins, but I am failing at including Autofac.Configuration in .NET Core 2.1
I have created small ASP.NET Core project and several controllers in other project. The Idea is to include those Controllers in ASP.NET Core project by Autofac.Configuration.

Here is autofac.json config file
`{"components": [{"type": "Controllers.UserController, Controllers","services": [{"type": "Common.IController, Common"}]}]}`

Here is code from Startup.cs
`public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddMvc().AddControllersAsServices();
            var builder = new ContainerBuilder();
            var mseConfig = new ConfigurationBuilder();
            mseConfig.AddJsonFile("autofac.json");
            var module = new ConfigurationModule(mseConfig.Build());
            builder.RegisterModule(module);
            builder.Populate(services);
            var container = builder.Build();
            return new AutofacServiceProvider(container);
        }`

The error I am receiving is "System.InvalidOperationException: 'The type 'Controllers.UserController, Controllers' could not be found. It may require assembly qualification, e.g. "MyType, MyAssembly".'"

Controllers.dll file is present in bin folder of ASP.NET Core project.

Any suggestions please?
regards

**Comment by tillig** [comment] 2018-10-08 14:12
This is very much a "how do I...?" sort of usage question. As noted in the issue template, have you tried [StackOverflow](http://stackoverflow.com) and tagged your question `autofac`? That's a good first stop.

When you post to StackOverflow, please:

- Include a link to the question here so folks can answer in one spot (StackOverflow).
- Add a full stack trace to the error - _when_ it gets thrown is just as important as _what_ it says.

Also, be aware that assembly loading in .NET Core is _very, very different_ than in .NET. The whole app doesn't just show up in the bin folder anymore; dependencies get located out of NuGet caches and things. You _may_ be having issues surrounding this. [This blog article](https://natemcmaster.com/blog/2018/07/25/netcore-plugins/) shows how a plugin framework for .NET Core works and notes that [there's no good doc](https://github.com/dotnet/docs/issues/2982) for the API that handles loading, though [it's on the TODO list](https://github.com/dotnet/docs/issues/1711). [There is a design document](https://github.com/dotnet/coreclr/blob/master/Documentation/design-docs/assemblyloadcontext.md) but that's about it. I personally haven't dived too deep in this territory, though it seems to be a common source of questions so I probably should.

Anyway, please try StackOverflow.

**Comment by tillig** [comment] 2018-10-08 14:16
Oh, I did just notice that you are registering the `Controllers.UserController` as `Common.IController` which is likely not the thing that ASP.NET Core wants to resolve. (ASP.NET Core, when using controllers as services, resolves the exact controller type, not an interface.)

I'm going to close this for now. Given Autofac.Configuration itself isn't involved in loading assemblies (nor is Autofac) this is likely going to be a challenge in ensuring the assembly can be found. If it turns out that you can point out a specific bug in Autofac.Configuration, please provide a minimal reproduction so we can see it and verify. We can reopen at that time. Thanks!

**Closed as completed by tillig** 2018-10-08 14:16 UTC

**Comment by opejanovic** [comment] 2018-10-08 14:34
I did try StackOverflow, but found no solution. I am onto this for the last 7 days.
"Common.IController" interface is just an example. Like I said, I used Autofac.Configuration to register bunch of controllers and to resolve them by Interface. I just failed doing the same within .NET Core 2.1

You said 
> Autofac.Configuration itself isn't involved in loading assemblies

but it fails in Autofac.Configuration.Core.ConfigurationExtensions, line 82
`return Assembly.Load(new AssemblyName(assemblyName));`
where it cannot find assembly defined in config file. 
It might be .NET Core issue with loading assemblies by assembly name, but since Autofac.Configuration is using Assembly.Load(new AssemblyName(assemblyName)); - is there any workaround?

I could write the reproduction steps, but to save time, can you point me to any working example of .NET Core + Autofac.Configuration where assemblies are specified in config file and registered/resolved by its Interface? No matter how simple it is

**Comment by tillig** [comment] 2018-10-08 14:36
Ah, right, I forgot about that one bit. Good one.

I'm guessing you didn't tag your question `autofac` since it didn't come up in any alerts. You also haven't posted your question here so we can follow up with it.

[Minor update: It appears that even `Assembly.Load` goes through the .NET Core assembly loader mechanism, so while we're making that call, you'll still need to handle custom assembly load logic to allow .NET Core to load your plugins.]

**Comment by tillig** [comment] 2018-10-08 14:38
OK, I found your question.
https://stackoverflow.com/questions/52682888/net-core-2-1-autofac-and-problem-with-injecting-controller

Apparently there's an issue with StackOverflow alerts - I'm not getting the emails anymore. I'll follow up with them.

**Comment by opejanovic** [comment] 2018-10-08 14:44
Yup that's the one :)
I just can't explain anymore to the others, the benefit of specifying assemblies in config.json file and benefit of using Autofac.Configuration for plugin architecture. So I came here.
Here is the scenario, I have three projects

1. ASP.NET Core api. This project references only Common project (the next one in the list)
2. Common project where Interface is (lets call it IController)
3. A project where is implementation of the interface, controller for example (references only Common project)

Using Autofac.Configuration I can specify which assembly to register/resolve and it can be used as plugin. I can inject any controller I want.
Sadly it doesn't work since I was not able to load assembly. I run out of ideas.

**Comment by tillig** [comment] 2018-10-08 14:47
I understand your description of the challenge, but unfortunately all this needs to be in a single place (so it's not people looking through comments and the question there, and looking through a discussion here) - help us help you. I left a comment over there explaining why it's difficult to answer the question. These are hard issues sometimes and I'm sorry you're having trouble, but you're also getting software _for free_ and support _for free_ from people who are doing all this work in their spare time entirely unpaid. You'll need to be patient and do more of the leg-work to try to solve the problem.

**Comment by opejanovic** [comment] 2018-10-08 14:56
Thanks for understanding, 
I am not expecting for somebody else to solve my problems, all I am asking, did anyone successfully implemented Autofac.Configuration and .NET Core and is there any working example?
regards
Ogi

**Comment by tillig** [comment] 2018-10-08 22:04
I have created [a working example in the Autofac Examples repo.](https://github.com/autofac/Examples/blob/master/src/ConfigurationExample/Program.cs) As suspected, the problem lies in how the .NET Core assembly loader does **NOT** just assume things in your bin folder are loadable. You absolutely need to tell .NET Core's assembly loader where to get assemblies that are not directly referenced. That's not an Autofac config thing, that's .NET Core and it's pretty confusing new loader system.

From here out, let's use the StackOverflow question if there's more so other people can also take advantage of it. I won't respond to additional stuff here. It sounds like you can probably close the question over there anyway and create a different question about how to ensure assembly loading is working for plugins.

The easiest test you can do from your code: If you do `Type.GetType("MyNamespace.MyType, MyAssembly")` and come out with a `null`, .NET Core is not finding your type and you need to handle assembly loading. You can mess around with the example program and comment out the custom assembly loading code to see that in action.

**Comment by opejanovic** [comment] 2018-10-09 08:09
Thank you a lot.
I really appreciate what you guys did with Autofac.Configuration

regards
